version: "3.8"

services:
  server:
    build: 
      context: .
      dockerfile: source/Dockerfile
    container_name: api_server  
    volumes:    
     - ./api/app/:/app
    ports:
     - 8778:80
#  db:
#    image: postgres:15-alpine
#    container_name: db
#    volumes:
#    - postgres_dict_data:/var/lib/postgresql/data/
#    ports:
#     - "5434:5432"
#    environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: postgres_db

#volumes:
#  postgres_dict_data: